server:
  port: 8095

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/BootMonoAsD72
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
# BirtOfDate için date format data bu şekilde girili, bu şekilde döner.
  jackson:
    date-format: dd/MM/yyyy
